name: branch-check
on:
  pull_request_target:
    types: [opened, edited, reopened]
jobs:
  branch-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: CodesmithLLC/assessment-auto-merge-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}